name: Deploy Eaglercraft Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync files to server
      run: rsync -avz --delete ./ user@server_ip:/path/to/server/

    - name: Restart server
      run: ssh user@server_ip 'bash /path/to/server/start.sh'
